### PR TITLE
Start default sc session when compiling

### LINKED ISSUE #56: On compiling, open a scratch document with syntax supercollider if needed
I was thinking that it would be nice if you are not already focused on a supercollider syntax document, then shift-command-K (or whatever you bind it for) would also open a blank scratch document and set the syntax.  

I often want to just open a supercollider session and I don't want to have to open my scratch.scd or use a blank window and then set the syntax. it should just be shift-command-K

### PR DESCRIPTION
**Pull request by gusano**
Fix #56

### CODE REVIEW

**Comment by crucialfelix** [comment]
Dude, you are on fire ! Looks great

**Comment by gusano** [comment]
it's something I wanted very much :jack_o_lantern:

**Comment by crucialfelix** [comment]
I'm not using sclang right now, but I would still like to write an
autocomplete provider for atom. They are easy to write. We would need to
either parse all included paths using ctags, or we get sclang to dump a
Jason file with all classes and methods.

Myself, I have no problem using autocomplete now with ctags, nut I manually
set up a project with symlinks that includes classlib and all instLled
quarks. Too much work for most people.

**Comment by gusano** [comment]
@crucialfelix dude, I know you're busy :baby_bottle: but I bump it anyway, so others can enjoy that feature ;)

**Comment by crucialfelix** [comment]
merci !

**Pull request merged**
